const masterCollegesData = [
  { rank: 1, name: "Gandhi Medical College", place: "Secunderabad", type: "Government", est: 1954, pg: "Yes (All)", rating: "4.6 ★", notes: "Apex College #1 in TS, 1200+ Bed Hospital" },
  { rank: 2, name: "Osmania Medical College", place: "Hyderabad", type: "Government", est: 1846, pg: "Yes (All)", rating: "4.6 ★", notes: "Oldest Premier Institute, Massive Patient Inflow" },
  { rank: 3, name: "ESIC Medical College & Hospital", place: "Sanath Nagar, Hyd", type: "Government (Central)", est: 2016, pg: "Yes (Super)", rating: "4.5 ★", notes: "Central Govt Stipend & World-Class Infra" },
  { rank: 4, name: "Kakatiya Medical College (KMC)", place: "Warangal", type: "Government", est: 1959, pg: "Yes (All)", rating: "4.4 ★", notes: "Top Govt College in North TS (MGM Hospital)" },
  { rank: 5, name: "Apollo Institute of Medical Sciences", place: "Jubilee Hills, Hyd", type: "Private (Cat-A)", est: 2012, pg: "Yes", rating: "4.4 ★", notes: "Top #1 Private College in TS, Apex Clinicals" },
  { rank: 6, name: "Kamineni Academy of Med Sci (KAMS)", place: "LB Nagar, Hyd", type: "Private (Cat-A)", est: 2012, pg: "Yes", rating: "4.3 ★", notes: "Prime Metro Location, High Patient Inflow" },
  { rank: 7, name: "Mamata Academy of Med Sci (MAMS)", place: "Bachupally, Hyd", type: "Private (Cat-A)", est: 2019, pg: "Yes", rating: "4.3 ★", notes: "Top Demanded Metro Private, Modern Campus" },
  { rank: 8, name: "Government Medical College", place: "Nizamabad", type: "Government", est: 2013, pg: "Yes", rating: "4.3 ★", notes: "Best 2013 Govt Batch, Full PG Departments" },
  { rank: 9, name: "Government Medical College", place: "Siddipet", type: "Government", est: 2018, pg: "Yes", rating: "4.2 ★", notes: "Excellent Campus, Fast Growing Hub" },
  { rank: 10, name: "Government Medical College", place: "Mahabubnagar", type: "Government", est: 2016, pg: "Yes", rating: "4.2 ★", notes: "Established Govt College, 500+ Bed Hospital" },
  { rank: 11, name: "Government Medical College", place: "Suryapet", type: "Government", est: 2019, pg: "Yes", rating: "4.1 ★", notes: "Active Multi-Speciality Hospital & PG Seats" },
  { rank: 12, name: "Government Medical College", place: "Nalgonda", type: "Government", est: 2019, pg: "Yes", rating: "4.1 ★", notes: "Good Highway Connectivity to Hyderabad" },
  { rank: 13, name: "RIMS (Rajiv Gandhi Inst. of Med Sci)", place: "Adilabad", type: "Government", est: 2008, pg: "Yes", rating: "4.1 ★", notes: "Established 2008 Govt Institute, Full PG" },
  { rank: 14, name: "Kamineni Institute of Med Sci (KIMS)", place: "Narketpally, Nalgonda", type: "Private (Cat-A)", est: 1999, pg: "Yes", rating: "4.2 ★", notes: "25+ Yr Legacy Private, 1000+ Bed Hospital" },
  { rank: 15, name: "Mamata Medical College", place: "Khammam", type: "Private (Cat-A)", est: 1998, pg: "Yes", rating: "4.3 ★", notes: "25+ Yr Legacy, Excellent Clinical Record" },
  { rank: 16, name: "S.V.S. Medical College", place: "Mahabubnagar", type: "Private (Cat-A)", est: 1999, pg: "Yes", rating: "4.2 ★", notes: "Legacy Private Campus, Massive Patient Outflow" },
  { rank: 17, name: "Bhaskar Medical College", place: "Moinabad, Rangareddy", type: "Private (Cat-A)", est: 2005, pg: "Yes", rating: "4.0 ★", notes: "Close to City, Strong Academics & Patient Load" },
  { rank: 18, name: "C. Ananda Rao Inst. of Med Sci (CAIMS)", place: "Karimnagar", type: "Private (Cat-A)", est: 2002, pg: "Yes", rating: "4.1 ★", notes: "Established North TS Private, Good Exposure" },
  { rank: 19, name: "Prathima Institute of Med Sci (PIMS)", place: "Nagunur, Karimnagar", type: "Private (Cat-A)", est: 2001, pg: "Yes", rating: "4.2 ★", notes: "Major Tertiary Care Hospital & PG Hub" },
  { rank: 20, name: "Medicity Institute of Med Sci (MIMS)", place: "Ghanpur, Medchal", type: "Private (Cat-A)", est: 2002, pg: "Yes", rating: "4.1 ★", notes: "Peaceful Campus, 750+ Bed Hospital" },
  { rank: 21, name: "Malla Reddy Inst. of Med Sci (MRIMS)", place: "Suraram, Hyd", type: "Private (Cat-A)", est: 2012, pg: "Yes", rating: "4.0 ★", notes: "Large Metro Campus, High Patient Load" },
  { rank: 22, name: "Malla Reddy Med College for Women", place: "Suraram, Hyd", type: "Private (Cat-A Women)", est: 2013, pg: "Yes", rating: "4.1 ★", notes: "Top Women's Medical College, Safe & Secure" },
  { rank: 23, name: "Government Medical College", place: "Ramagundam", type: "Government", est: 2022, pg: "Yes", rating: "4.0 ★", notes: "Industrial Belt Hospital, Active PG Seats" },
  { rank: 24, name: "Government Medical College", place: "Sangareddy", type: "Government", est: 2022, pg: "No", rating: "4.0 ★", notes: "Proximity to Hyd, Good District Hospital" },
  { rank: 25, name: "Government Medical College", place: "Karimnagar", type: "Government", est: 2023, pg: "No", rating: "4.0 ★", notes: "District HQ Location, High Patient Base" },
  { rank: 26, name: "Government Medical College", place: "Khammam", type: "Government", est: 2023, pg: "No", rating: "4.0 ★", notes: "Good District Hospital Attachment" },
  { rank: 27, name: "Government Medical College", place: "Wanaparthy", type: "Government", est: 2022, pg: "No", rating: "3.9 ★", notes: "Functional District Hospital" },
  { rank: 28, name: "Government Medical College", place: "Nagarkurnool", type: "Government", est: 2022, pg: "No", rating: "3.9 ★", notes: "Functional District Hospital" },
  { rank: 29, name: "MNR Medical College & Hospital", place: "Sangareddy", type: "Private (Cat-A)", est: 2002, pg: "Yes", rating: "3.9 ★", notes: "Established 2002 Private, Full PG" },
  { rank: 30, name: "Dr. Patnam Mahender Reddy IMS", place: "Chevella, Rangareddy", type: "Private (Cat-A)", est: 2019, pg: "No", rating: "3.9 ★", notes: "Near Chevella, Good Infrastructure" },
  { rank: 31, name: "CMR Institute of Medical Sciences", place: "Kandlakoya, Medchal", type: "Private (Cat-A)", est: 2023, pg: "No", rating: "4.1 ★", notes: "Modern Campus, Fast Growing Patient Load" },
  { rank: 32, name: "Arundathi Institute of Med Sci", place: "Dundigal, Hyd", type: "Private (Cat-A)", est: 2023, pg: "No", rating: "4.0 ★", notes: "Near Dundigal, Brand New Campus" },
  { rank: 33, name: "RVM Medical College", place: "Mulugu, Medak", type: "Private (Cat-A)", est: 2016, pg: "Yes", rating: "3.9 ★", notes: "Good Hospital Attachment & PG Courses" },
  { rank: 34, name: "Prathima Relief Inst. of Med Sci (PMR)", place: "Warangal", type: "Private (Cat-A)", est: 2024, pg: "No", rating: "3.9 ★", notes: "New Unit of Prathima Group in Warangal" },
  { rank: 35, name: "Government Medical College", place: "Vikarabad", type: "Government", est: 2023, pg: "No", rating: "3.8 ★", notes: "Functional District Hospital" },
  { rank: 36, name: "Government Medical College", place: "Jangaon", type: "Government", est: 2023, pg: "No", rating: "3.8 ★", notes: "Developing District Campus" },
  { rank: 37, name: "Government Medical College", place: "Bhadradri Kothagudem", type: "Government", est: 2022, pg: "No", rating: "3.8 ★", notes: "Functional District Hospital" },
  { rank: 38, name: "Government Medical College", place: "Jagtial", type: "Government", est: 2022, pg: "No", rating: "3.8 ★", notes: "Functional District Hospital" },
  { rank: 39, name: "Government Medical College", place: "Mancherial", type: "Government", est: 2022, pg: "No", rating: "3.8 ★", notes: "Functional District Hospital" },
  { rank: 40, name: "Government Medical College", place: "Mahabubabad", type: "Government", est: 2022, pg: "No", rating: "3.8 ★", notes: "Functional District Hospital" },
  { rank: 41, name: "Government Medical College", place: "Rajanna Sircilla", type: "Government", est: 2023, pg: "No", rating: "3.8 ★", notes: "Developing District Campus" },
  { rank: 42, name: "Government Medical College", place: "Nirmal", type: "Government", est: 2023, pg: "No", rating: "3.8 ★", notes: "Developing District Campus" },
  { rank: 43, name: "Government Medical College", place: "Jayashankar Bhupalpally", type: "Government", est: 2023, pg: "No", rating: "3.7 ★", notes: "Remote District GMC" },
  { rank: 44, name: "Government Medical College", place: "Kamareddy", type: "Government", est: 2023, pg: "No", rating: "3.7 ★", notes: "Developing District Campus" },
  { rank: 45, name: "Government Medical College", place: "Kumuram Bheem Asifabad", type: "Government", est: 2023, pg: "No", rating: "3.7 ★", notes: "Tribal District GMC" },
  { rank: 46, name: "Government Medical College", place: "Quthbullapur", type: "Government", est: 2024, pg: "No", rating: "3.8 ★", notes: "Urban Location (Medchal), New Infra" },
  { rank: 47, name: "Deccan College of Medical Sciences", place: "Kanchanbagh, Hyd", type: "Private (Minority)", est: 1984, pg: "Yes", rating: "4.4 ★", notes: "Legacy Muslim Minority, Owaisi Hospital" },
  { rank: 48, name: "Shadan Institute of Medical Sciences", place: "Himayathsagar, Hyd", type: "Private (Minority)", est: 2005, pg: "Yes", rating: "4.2 ★", notes: "Established Muslim Minority, Full PG" },
  { rank: 49, name: "Ayaan Institute of Medical Sciences", place: "Moinabad", type: "Private (Minority)", est: 2018, pg: "No", rating: "3.8 ★", notes: "Private Muslim Minority" },
  { rank: 50, name: "Dr VRK Women's Medical College", place: "Moinabad", type: "Private (Minority Women)", est: 2010, pg: "No", rating: "3.8 ★", notes: "Women's Muslim Minority" },
  { rank: 51, name: "Father Colombo Inst. of Med Sci", place: "Warangal", type: "Private (Cat-A)", est: 2023, pg: "No", rating: "3.8 ★", notes: "New Private College in Warangal" },
  { rank: 52, name: "Nova Institute of Medical Sciences", place: "Hayathnagar, Hyd", type: "Private (Cat-A)", est: 2024, pg: "No", rating: "3.7 ★", notes: "Newly Permitted Private College" },
  { rank: 53, name: "Government Medical College", place: "Medak", type: "Government", est: 2024, pg: "No", rating: "3.6 ★", notes: "2024 Batch, Hospital Construction Stage" },
  { rank: 54, name: "Government Medical College", place: "Maheshwaram", type: "Government", est: 2024, pg: "No", rating: "3.6 ★", notes: "2024 Batch, Developing Infra" },
  { rank: 55, name: "Government Medical College", place: "Yadadri Bhuvanagiri", type: "Government", est: 2024, pg: "No", rating: "3.6 ★", notes: "2024 Batch, Temporary Campus" },
  { rank: 56, name: "Government Medical College", place: "Kodangal", type: "Government", est: 2024, pg: "No", rating: "3.5 ★", notes: "2024 Batch, Remote Location" },
  { rank: 57, name: "Government Medical College", place: "Narsampet", type: "Government", est: 2024, pg: "No", rating: "3.5 ★", notes: "2024 Batch, Temporary Facilities" },
  { rank: 58, name: "Government Medical College", place: "Jogulamba Gadwal", type: "Government", est: 2024, pg: "No", rating: "3.5 ★", notes: "2024 Batch, Border District" },
  { rank: 59, name: "Government Medical College", place: "Mulugu", type: "Government", est: 2024, pg: "No", rating: "3.5 ★", notes: "2024 Batch, Remote Tribal Region" },
  { rank: 60, name: "Government Medical College", place: "Narayanpet", type: "Government", est: 2024, pg: "No", rating: "3.5 ★", notes: "2024 Batch, Border District" },
  { rank: 61, name: "Maheshwara Medical College", place: "Patancheru, Medak", type: "Private (Cat-A)", est: 2016, pg: "No", rating: "3.2 ★", notes: "Not Recommended (NMC Audit Concerns)" },
  { rank: 62, name: "Mahavir Institute of Medical Sciences", place: "Vikarabad", type: "Private (Cat-A)", est: 2016, pg: "No", rating: "3.3 ★", notes: "Not Recommended (Low Patient Load)" },
  { rank: 63, name: "Surabhi Institute of Medical Sciences", place: "Siddipet", type: "Private (Cat-A)", est: 2019, pg: "No", rating: "3.3 ★", notes: "Not Recommended (Low Patient Load)" },
  { rank: 64, name: "TRR Institute of Medical Sciences", place: "Patancheru", type: "Private (Cat-A)", est: 2020, pg: "No", rating: "3.2 ★", notes: "Not Recommended (Low Patient Load)" },
  { rank: 65, name: "Neelima Institute of Medical Sciences", place: "Medchal", type: "Private (Cat-A)", est: 2023, pg: "No", rating: "3.5 ★", notes: "Newer Private, Developing Patient Base" },
  { rank: 66, name: "Raja Rajeshwari Inst. of Med Sci", place: "Patancheru", type: "Private (Cat-A Girls)", est: 2024, pg: "No", rating: "3.4 ★", notes: "Newly Permitted Girls Private College" }
];
